-- Crear tabla

USE metro_cdmx;

-- CREA TABLA LINEAS
CREATE TABLE `lineas` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,

  `nombre` VARCHAR(10) NOT NULL,
  `color` VARCHAR(15) NOT NULL,

  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (id)
)
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;


-- CREA TABLA TRENES
CREATE TABLE `trenes` (
  `numero_serie` VARCHAR(10) NOT NULL,

  `linea_id`  BIGINT(20) UNSIGNED NOT NULL,
  `tipo` TINYINT(4) NOT NULL,
  `anio` INT(4) NOT NULL,

  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (numero_serie),
  CONSTRAINT `trenes_linea_id_foreign`
  FOREIGN KEY (`linea_id`) REFERENCES `lineas` (`id`)
)
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;


-- CREA TABLA ESTACIONES
CREATE TABLE `estaciones` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,

  `nombre` VARCHAR(50) NOT NULL,

  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (id)
) 
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;


-- CREA TABLA ESTACIONES
CREATE TABLE `estaciones_borrar` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,

  `nombre` BIGINT(20) NOT NULL,

  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (id)
) 
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;

