CREATE TABLE `conductores` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,

  `nombre` VARCHAR(20) NOT NULL,
  `status` BOOLEAN NOT NULL DEFAULT false,

  `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY(id)
)
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;